### ISSUE TITLE
Columns of manifest should match sync function

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/annotationUI#1]
The synapse sync command takes a manifest where the first three columns are
```id```
```name```
```parent```

name should replace fileName and id should replace synapseId and parent should be added.

**Comment by teslajoy** [comment]
Done!  https://github.com/Sage-Bionetworks/annotationUI/commit/d3ccbb5e32dbce02919a99e16ba8ee31f8b2d3f4

Takes a minute to sync in with the live UI
