### ISSUE TITLE
shopping cart for keys

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/annotationUI#14]
Summarizing for @amapeters, correct me if I'm wrong!

Want to send collaborators a manifest + definitions, but only of a subset of keys from different modules. It would be nice to have a table view of all the module + keys with a selector or checkbox of some sort. Then, export works as it currently does but only exports the things selected.

**Comment by amapeters** [comment]
Correct!

**Comment by teslajoy** [comment]
Although not ideal from a UI/UX stand point, I made a quick fix to this issue. 

1. Use the global search box to search the entire table for the desired keywords. This will find results in all columns. 
2. Select the modules that you need to subset data and get the desired final annotation table. 
3. You may expand the table view by selecting 1000 rows to be shown.
4. Select/highlight a row with the keys that you'd like. You don't have to select all the rows. Just one row with the desired key would do the trick.

**Comment by teslajoy** [comment]
found a bug :|

**Comment by teslajoy** [comment]
The issue was in DT::renderDataTable arguments. _pageLength_ should be defined before _lengthMenu_. Also, for the app to know which user's session it's pulling rows down from, server side processing argument should be set to false.  

The logic would work for both download buttons.
