### ISSUE TITLE
panel to view keys quickly in UI

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/annotationUI#19]
Another feature request...

If I want to quickly get an idea of what keys exist in a given module, I either have to click through all of the pages of values in the table, or I have to download the manifest and look there. 

If possible, I'd like to be able to see the second tab of the manifest ("keyDescription"), but in the shiny app, so I don't have to download a manifest just to figure out what keys are in a module or set of modules. 

Thanks!

**Comment by teslajoy** [comment]
Will do... Great idea! 
as soon as I get this analysis running I'll jump to it 👍
