### ISSUE TITLE
Add the ability to export to json

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/annotationUI#2]
In addition to exporting a manifest, can we also export the combined json file.  A user at OHSU requested this.

**Comment by teslajoy** [comment]
This would be a nice integration to @xindiguo 's code too since it takes a json parameter as input. I'll first try to call a python script in R to do this. json and R don't like to dance with each other very well.

**Comment by sgosline** [comment]
Yes, working with the sync_manifest would be a great benefit - only one user so far has actually said he *prefers* json ;)

**Comment by teslajoy** [comment]
Initial button has been implemented. :)
