### ISSUE TITLE
Error in checkboxGroupInput

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/annotationUI#4]
When trying to start the app like:

```
shiny::runGitHub('Sage-Bionetworks/annotationUI')
```

I get:

```
Warning: Error in checkboxGroupInput: unused arguments (choiceNames = categories, choiceValues = categories)
Stack trace (innermost first):
    49: checkboxGroupInput
    48: sidebarMenu
    47: tag
    46: tags$section
    45: tag
    44: tags$aside
    43: dashboardSidebar
     3: runApp
     2: runUrl
     1: shiny::runGitHub
Error : unused arguments (choiceNames = categories, choiceValues = categories)
```

**Comment by teslajoy** [comment]
@kdaily Do you login to synapse successfully? I think your 'categories' var is null and thats the data from synapse table syn10005388 which you have admin permissions on.

**Comment by kdaily** [comment]
It's a version problem - the parameters `choiceNames` and `choiceValues` come from a more recent version of the `shiny` package than I have (`0.14.2`)
