### ISSUE TITLE
Rename 'projects' to 'modules' or something more generic

### ISSUE THREAD

**Issue by sgosline** [Sage-Bionetworks/annotationUI#8]
Not all annotation 'projects' are actually projects and it's confusing to see this in the UI. Can we just make this 'modules' or 'topics'?

**Comment by teslajoy** [comment]
Agree. Modules is a great term for the data we have. For uploading however, users _project_ would probably make more sense. I will change the UI on aug 8th on site.

**Comment by teslajoy** [comment]
Done!
https://www.synapse.org/#!Synapse:syn10242922/tables/
will update shortly https://shiny.synapse.org/users/nsanati/annotationUI/
